# Valores extraídos de tu Angular environment.ts
entra.tenant-id=aeb5f35e-b0f1-4661-9bf0-506586dad4f1
entra.api-client-id=6bb50e2a-1850-4994-88b4-ce9327a8a1ff
# Puertos locales (como lo tenías en tus instrucciones)
server.port=8080
services.orders.url=http://localhost:8081
services.catalog.url=http://localhost:8082
